// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: account.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountCreateReq) Reset() {
	*x = AccountCreateReq{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreateReq) ProtoMessage() {}

func (x *AccountCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreateReq.ProtoReflect.Descriptor instead.
func (*AccountCreateReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountCreateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AccountCreateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountCreateRes) Reset() {
	*x = AccountCreateRes{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreateRes) ProtoMessage() {}

func (x *AccountCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreateRes.ProtoReflect.Descriptor instead.
func (*AccountCreateRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountCreateRes) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AccountBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountBalanceReq) Reset() {
	*x = AccountBalanceReq{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalanceReq) ProtoMessage() {}

func (x *AccountBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalanceReq.ProtoReflect.Descriptor instead.
func (*AccountBalanceReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *AccountBalanceReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type AccountBalanceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       uint64                 `protobuf:"varint,1,opt,name=Balance,proto3" json:"Balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountBalanceRes) Reset() {
	*x = AccountBalanceRes{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBalanceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalanceRes) ProtoMessage() {}

func (x *AccountBalanceRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalanceRes.ProtoReflect.Descriptor instead.
func (*AccountBalanceRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *AccountBalanceRes) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\".\n" +
	"\x10AccountCreateReq\x12\x1a\n" +
	"\bPassword\x18\x01 \x01(\tR\bPassword\",\n" +
	"\x10AccountCreateRes\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\tR\aAddress\"-\n" +
	"\x11AccountBalanceReq\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\tR\aAddress\"-\n" +
	"\x11AccountBalanceRes\x12\x18\n" +
	"\aBalance\x18\x01 \x01(\x04R\aBalance2z\n" +
	"\aAccount\x125\n" +
	"\rAccountCreate\x12\x11.AccountCreateReq\x1a\x11.AccountCreateRes\x128\n" +
	"\x0eAccountBalance\x12\x12.AccountBalanceReq\x1a\x12.AccountBalanceResB\aZ\x05./rpcb\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_account_proto_goTypes = []any{
	(*AccountCreateReq)(nil),  // 0: AccountCreateReq
	(*AccountCreateRes)(nil),  // 1: AccountCreateRes
	(*AccountBalanceReq)(nil), // 2: AccountBalanceReq
	(*AccountBalanceRes)(nil), // 3: AccountBalanceRes
}
var file_account_proto_depIdxs = []int32{
	0, // 0: Account.AccountCreate:input_type -> AccountCreateReq
	2, // 1: Account.AccountBalance:input_type -> AccountBalanceReq
	1, // 2: Account.AccountCreate:output_type -> AccountCreateRes
	3, // 3: Account.AccountBalance:output_type -> AccountBalanceRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
