// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: block.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Parent        string                 `protobuf:"bytes,3,opt,name=Parent,proto3" json:"Parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSearchReq) Reset() {
	*x = BlockSearchReq{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSearchReq) ProtoMessage() {}

func (x *BlockSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSearchReq.ProtoReflect.Descriptor instead.
func (*BlockSearchReq) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

func (x *BlockSearchReq) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BlockSearchReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BlockSearchReq) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type BlockSearchRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         []byte                 `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSearchRes) Reset() {
	*x = BlockSearchRes{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSearchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSearchRes) ProtoMessage() {}

func (x *BlockSearchRes) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSearchRes.ProtoReflect.Descriptor instead.
func (*BlockSearchRes) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *BlockSearchRes) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\"T\n" +
	"\x0eBlockSearchReq\x12\x16\n" +
	"\x06Number\x18\x01 \x01(\x04R\x06Number\x12\x12\n" +
	"\x04Hash\x18\x02 \x01(\tR\x04Hash\x12\x16\n" +
	"\x06Parent\x18\x03 \x01(\tR\x06Parent\"&\n" +
	"\x0eBlockSearchRes\x12\x14\n" +
	"\x05Block\x18\x01 \x01(\fR\x05Block2:\n" +
	"\x05Block\x121\n" +
	"\vBlockSearch\x12\x0f.BlockSearchReq\x1a\x0f.BlockSearchRes0\x01B\aZ\x05./rpcb\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_block_proto_goTypes = []any{
	(*BlockSearchReq)(nil), // 0: BlockSearchReq
	(*BlockSearchRes)(nil), // 1: BlockSearchRes
}
var file_block_proto_depIdxs = []int32{
	0, // 0: Block.BlockSearch:input_type -> BlockSearchReq
	1, // 1: Block.BlockSearch:output_type -> BlockSearchRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
