// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: block.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenesisSyncReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisSyncReq) Reset() {
	*x = GenesisSyncReq{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisSyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisSyncReq) ProtoMessage() {}

func (x *GenesisSyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisSyncReq.ProtoReflect.Descriptor instead.
func (*GenesisSyncReq) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

type GenesisSyncRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genesis       []byte                 `protobuf:"bytes,1,opt,name=Genesis,proto3" json:"Genesis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisSyncRes) Reset() {
	*x = GenesisSyncRes{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisSyncRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisSyncRes) ProtoMessage() {}

func (x *GenesisSyncRes) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisSyncRes.ProtoReflect.Descriptor instead.
func (*GenesisSyncRes) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *GenesisSyncRes) GetGenesis() []byte {
	if x != nil {
		return x.Genesis
	}
	return nil
}

type BlockReceiveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         []byte                 `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockReceiveReq) Reset() {
	*x = BlockReceiveReq{}
	mi := &file_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockReceiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReceiveReq) ProtoMessage() {}

func (x *BlockReceiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReceiveReq.ProtoReflect.Descriptor instead.
func (*BlockReceiveReq) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{2}
}

func (x *BlockReceiveReq) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

type BlockReceiveRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockReceiveRes) Reset() {
	*x = BlockReceiveRes{}
	mi := &file_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockReceiveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReceiveRes) ProtoMessage() {}

func (x *BlockReceiveRes) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReceiveRes.ProtoReflect.Descriptor instead.
func (*BlockReceiveRes) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{3}
}

type BlockSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Parent        string                 `protobuf:"bytes,3,opt,name=Parent,proto3" json:"Parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSearchReq) Reset() {
	*x = BlockSearchReq{}
	mi := &file_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSearchReq) ProtoMessage() {}

func (x *BlockSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSearchReq.ProtoReflect.Descriptor instead.
func (*BlockSearchReq) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{4}
}

func (x *BlockSearchReq) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BlockSearchReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BlockSearchReq) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type BlockSearchRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         []byte                 `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSearchRes) Reset() {
	*x = BlockSearchRes{}
	mi := &file_block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSearchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSearchRes) ProtoMessage() {}

func (x *BlockSearchRes) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSearchRes.ProtoReflect.Descriptor instead.
func (*BlockSearchRes) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{5}
}

func (x *BlockSearchRes) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

type BlockSyncReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSyncReq) Reset() {
	*x = BlockSyncReq{}
	mi := &file_block_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSyncReq) ProtoMessage() {}

func (x *BlockSyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSyncReq.ProtoReflect.Descriptor instead.
func (*BlockSyncReq) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{6}
}

func (x *BlockSyncReq) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type BlockSyncRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         []byte                 `protobuf:"bytes,1,opt,name=Block,proto3" json:"Block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSyncRes) Reset() {
	*x = BlockSyncRes{}
	mi := &file_block_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSyncRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSyncRes) ProtoMessage() {}

func (x *BlockSyncRes) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSyncRes.ProtoReflect.Descriptor instead.
func (*BlockSyncRes) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{7}
}

func (x *BlockSyncRes) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\"\x10\n" +
	"\x0eGenesisSyncReq\"*\n" +
	"\x0eGenesisSyncRes\x12\x18\n" +
	"\aGenesis\x18\x01 \x01(\fR\aGenesis\"'\n" +
	"\x0fBlockReceiveReq\x12\x14\n" +
	"\x05Block\x18\x01 \x01(\fR\x05Block\"\x11\n" +
	"\x0fBlockReceiveRes\"T\n" +
	"\x0eBlockSearchReq\x12\x16\n" +
	"\x06Number\x18\x01 \x01(\x04R\x06Number\x12\x12\n" +
	"\x04Hash\x18\x02 \x01(\tR\x04Hash\x12\x16\n" +
	"\x06Parent\x18\x03 \x01(\tR\x06Parent\"&\n" +
	"\x0eBlockSearchRes\x12\x14\n" +
	"\x05Block\x18\x01 \x01(\fR\x05Block\"&\n" +
	"\fBlockSyncReq\x12\x16\n" +
	"\x06Number\x18\x01 \x01(\x04R\x06Number\"$\n" +
	"\fBlockSyncRes\x12\x14\n" +
	"\x05Block\x18\x01 \x01(\fR\x05Block2\xce\x01\n" +
	"\x05Block\x121\n" +
	"\vBlockSearch\x12\x0f.BlockSearchReq\x1a\x0f.BlockSearchRes0\x01\x12/\n" +
	"\vGenesisSync\x12\x0f.GenesisSyncReq\x1a\x0f.GenesisSyncRes\x12+\n" +
	"\tBlockSync\x12\r.BlockSyncReq\x1a\r.BlockSyncRes0\x01\x124\n" +
	"\fBlockReceive\x12\x10.BlockReceiveReq\x1a\x10.BlockReceiveRes(\x01B\aZ\x05./rpcb\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_block_proto_goTypes = []any{
	(*GenesisSyncReq)(nil),  // 0: GenesisSyncReq
	(*GenesisSyncRes)(nil),  // 1: GenesisSyncRes
	(*BlockReceiveReq)(nil), // 2: BlockReceiveReq
	(*BlockReceiveRes)(nil), // 3: BlockReceiveRes
	(*BlockSearchReq)(nil),  // 4: BlockSearchReq
	(*BlockSearchRes)(nil),  // 5: BlockSearchRes
	(*BlockSyncReq)(nil),    // 6: BlockSyncReq
	(*BlockSyncRes)(nil),    // 7: BlockSyncRes
}
var file_block_proto_depIdxs = []int32{
	4, // 0: Block.BlockSearch:input_type -> BlockSearchReq
	0, // 1: Block.GenesisSync:input_type -> GenesisSyncReq
	6, // 2: Block.BlockSync:input_type -> BlockSyncReq
	2, // 3: Block.BlockReceive:input_type -> BlockReceiveReq
	5, // 4: Block.BlockSearch:output_type -> BlockSearchRes
	1, // 5: Block.GenesisSync:output_type -> GenesisSyncRes
	7, // 6: Block.BlockSync:output_type -> BlockSyncRes
	3, // 7: Block.BlockReceive:output_type -> BlockReceiveRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
