// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: node.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerDiscoverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=Peer,proto3" json:"Peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerDiscoverReq) Reset() {
	*x = PeerDiscoverReq{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerDiscoverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerDiscoverReq) ProtoMessage() {}

func (x *PeerDiscoverReq) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerDiscoverReq.ProtoReflect.Descriptor instead.
func (*PeerDiscoverReq) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *PeerDiscoverReq) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

type PeerDiscoverRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []string               `protobuf:"bytes,1,rep,name=Peers,proto3" json:"Peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerDiscoverRes) Reset() {
	*x = PeerDiscoverRes{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerDiscoverRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerDiscoverRes) ProtoMessage() {}

func (x *PeerDiscoverRes) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerDiscoverRes.ProtoReflect.Descriptor instead.
func (*PeerDiscoverRes) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *PeerDiscoverRes) GetPeers() []string {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\"%\n" +
	"\x0fPeerDiscoverReq\x12\x12\n" +
	"\x04Peer\x18\x01 \x01(\tR\x04Peer\"'\n" +
	"\x0fPeerDiscoverRes\x12\x14\n" +
	"\x05Peers\x18\x01 \x03(\tR\x05Peers2:\n" +
	"\x04Node\x122\n" +
	"\fPeerDiscover\x12\x10.PeerDiscoverReq\x1a\x10.PeerDiscoverResB\aZ\x05./rpcb\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_node_proto_goTypes = []any{
	(*PeerDiscoverReq)(nil), // 0: PeerDiscoverReq
	(*PeerDiscoverRes)(nil), // 1: PeerDiscoverRes
}
var file_node_proto_depIdxs = []int32{
	0, // 0: Node.PeerDiscover:input_type -> PeerDiscoverReq
	1, // 1: Node.PeerDiscover:output_type -> PeerDiscoverRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
