// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: tx.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	Account       string                 `protobuf:"bytes,4,opt,name=Account,proto3" json:"Account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSearchReq) Reset() {
	*x = TxSearchReq{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSearchReq) ProtoMessage() {}

func (x *TxSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSearchReq.ProtoReflect.Descriptor instead.
func (*TxSearchReq) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *TxSearchReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TxSearchReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TxSearchReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TxSearchReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type TxSearchRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []byte                 `protobuf:"bytes,1,opt,name=Tx,proto3" json:"Tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSearchRes) Reset() {
	*x = TxSearchRes{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSearchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSearchRes) ProtoMessage() {}

func (x *TxSearchRes) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSearchRes.ProtoReflect.Descriptor instead.
func (*TxSearchRes) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *TxSearchRes) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

type TxSignReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	Value         uint64                 `protobuf:"varint,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSignReq) Reset() {
	*x = TxSignReq{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSignReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSignReq) ProtoMessage() {}

func (x *TxSignReq) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSignReq.ProtoReflect.Descriptor instead.
func (*TxSignReq) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *TxSignReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TxSignReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TxSignReq) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TxSignReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TxSignRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []byte                 `protobuf:"bytes,1,opt,name=Tx,proto3" json:"Tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSignRes) Reset() {
	*x = TxSignRes{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSignRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSignRes) ProtoMessage() {}

func (x *TxSignRes) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSignRes.ProtoReflect.Descriptor instead.
func (*TxSignRes) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *TxSignRes) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\"_\n" +
	"\vTxSearchReq\x12\x12\n" +
	"\x04Hash\x18\x01 \x01(\tR\x04Hash\x12\x12\n" +
	"\x04From\x18\x02 \x01(\tR\x04From\x12\x0e\n" +
	"\x02To\x18\x03 \x01(\tR\x02To\x12\x18\n" +
	"\aAccount\x18\x04 \x01(\tR\aAccount\"\x1d\n" +
	"\vTxSearchRes\x12\x0e\n" +
	"\x02Tx\x18\x01 \x01(\fR\x02Tx\"a\n" +
	"\tTxSignReq\x12\x12\n" +
	"\x04From\x18\x01 \x01(\tR\x04From\x12\x0e\n" +
	"\x02To\x18\x02 \x01(\tR\x02To\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\x04R\x05Value\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\"\x1b\n" +
	"\tTxSignRes\x12\x0e\n" +
	"\x02Tx\x18\x01 \x01(\fR\x02Tx2P\n" +
	"\x02Tx\x12(\n" +
	"\bTxSearch\x12\f.TxSearchReq\x1a\f.TxSearchRes0\x01\x12 \n" +
	"\x06TxSign\x12\n" +
	".TxSignReq\x1a\n" +
	".TxSignResB\aZ\x05./rpcb\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tx_proto_goTypes = []any{
	(*TxSearchReq)(nil), // 0: TxSearchReq
	(*TxSearchRes)(nil), // 1: TxSearchRes
	(*TxSignReq)(nil),   // 2: TxSignReq
	(*TxSignRes)(nil),   // 3: TxSignRes
}
var file_tx_proto_depIdxs = []int32{
	0, // 0: Tx.TxSearch:input_type -> TxSearchReq
	2, // 1: Tx.TxSign:input_type -> TxSignReq
	1, // 2: Tx.TxSearch:output_type -> TxSearchRes
	3, // 3: Tx.TxSign:output_type -> TxSignRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
